export enum EnvName {
    CONFIG_PATH = 'WS_SCRCPY_CONFIG',
    WS_SCRCPY_PATHNAME = 'WS_SCRCPY_PATHNAME',
    AUTH_USER = 'WS_SCRCPY_AUTH_USER',
    AUTH_PASSWORD = 'WS_SCRCPY_AUTH_PASSWORD',
    AUTH_PASSWORD_FILE = 'WS_SCRCPY_AUTH_PASSWORD_FILE',
}
